# $1 - platform name
# $2 - runner workspace
# $3 - config
# $4 - toolset (MSVC)

cd "$2"
mkdir build
cd ./build

if [ "$1" = "win10" ]; then
  cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A $4 -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_BUILD_TESTS=ON -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_INSTALL_PREFIX=install ..
fi

if [ "$1" = "win10-dev" ]; then
  cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A $4 -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_BUILD_TESTS=ON -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_INSTALL_PREFIX=install -DDILIGENT_DEVELOPMENT=ON ..
fi

if [ "$1" = "win8" ]; then
  cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A $4 -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_BUILD_TESTS=ON -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_SYSTEM_VERSION=8.1 ..
fi

if [ "$1" = "uwp" ]; then
  cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A $4 -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_INSTALL_PREFIX=install ..
fi

if [ "$1" = "macos" ]; then
  cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_BUILD_TESTS=ON -DVULKAN_SDK="$VULKAN_SDK" -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_INSTALL_PREFIX=install ..
fi

if [ "$1" = "ios" ]; then
  cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_BUILD_TESTS=ON -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_OSX_ARCHITECTURES=arm64 -DVULKAN_SDK="$VULKAN_SDK" -DDILIGENT_NO_FORMAT_VALIDATION=ON -DCMAKE_INSTALL_PREFIX=install ..
fi

if [ "$1" = "linux" ]; then
  cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$3 -DDILIGENT_BUILD_TESTS=ON -DDILIGENT_NO_FORMAT_VALIDATION=ON $4 -DCMAKE_INSTALL_PREFIX=install ..
fi
