name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Android

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Format validation
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/FormatValidation
        ./validate_format_linux.sh

    - name: Set up Java 8
      if: success()
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Gradle
      if: success()
      run: |
        cd ./BuildTools/Android
        chmod +x gradlew
        ./gradlew buildDebug
