name: Android

on: [push, pull_request]

jobs:
  build-armeabi-v7a:
    runs-on: ubuntu-latest
    name: Android ARM32

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Format validation
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/FormatValidation
        ./validate_format_linux.sh

    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Gradle
      env:
        ANDROID_ARCH: armeabi-v7a
      run: |
        cd ./BuildTools/Android
        chmod +x gradlew
        ./gradlew buildDebug

  build-arm64-v8a:
    runs-on: ubuntu-latest
    name: Android ARM64

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Format validation
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/BuildTools/FormatValidation
        ./validate_format_linux.sh

    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Gradle
      env:
        ANDROID_ARCH: arm64-v8a
      run: |
        cd ./BuildTools/Android
        chmod +x gradlew
        ./gradlew buildDebug
